apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-training
spec:
  template:
    spec:
      containers:
      - name: mnist-training
        image: gcr.io/[PROJECT_ID]/mnist-training:latest
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4